spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Clave secreta para JWT, no valida en producción
jwt.secret=iX2HlM19AxLltLPs13kCh98BA8ENOzC9Xwidfyit92U=
