spring.application.name=auth

spring.profiles.active=${PROD:dev}

spring.datasource.url=jdbc:postgresql://dpg-d8jok3k2m8qs739bf09g-a.oregon-postgres.render.com/db_infernum
spring.datasource.username=infernum
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_KEY}
